/**
 * Turns the `components.schemas` of the OpenAPI specification into zod schemas, one exported constant per named
 * schema, as TypeScript source. Pure, so it can be unit tested; `generate_schemas.mts` is the CLI around it.
 *
 * The output is meant for validating API *responses*, which shapes three choices that differ from a literal
 * translation of the specification:
 *
 *   - Every object is a `z.looseObject()`, so a field the API starts returning before the specification documents
 *     it passes through untouched. `additionalProperties: false` is ignored for the same reason. This is the
 *     Python client's `extra='allow'`.
 *   - Every string enum accepts any other string too (`z.enum([...]).or(z.string())`), so a value the API adds
 *     does not fail every response that carries it. This is the Python client's `Literal[...] | str`.
 *   - `format: date-time` becomes `z.date()`, because the client converts those fields into `Date` objects
 *     before a response is validated, and the generated types say `Date` for the same reason.
 *
 * A `default` is deliberately not applied: it says what the server fills in when a request omits the field, not
 * what a response carries, so the parsed value stays identical to the response. Every other constraint the
 * specification states -- `required`, `minimum`, `pattern`, ... -- is kept, so a response that violates the
 * documented contract is reported rather than passed on.
 *
 * Only the JSON Schema vocabulary the specification actually uses is supported. Anything else fails generation
 * rather than being silently dropped, so a new construct shows up as a build failure in the nightly regeneration
 * instead of as a schema that accepts less or more than the specification says.
 */

/** The subset of a JSON Schema object this emitter understands. */
export interface SchemaNode {
    $ref?: string;
    type?: string | string[];
    properties?: Record<string, SchemaNode>;
    required?: string[];
    additionalProperties?: boolean | SchemaNode;
    items?: SchemaNode;
    allOf?: SchemaNode[];
    anyOf?: SchemaNode[];
    oneOf?: SchemaNode[];
    discriminator?: { propertyName: string; mapping?: Record<string, string> };
    enum?: unknown[];
    const?: unknown;
    format?: string;
    pattern?: string;
    minimum?: number;
    maximum?: number;
    exclusiveMinimum?: number;
    exclusiveMaximum?: number;
    multipleOf?: number;
    minLength?: number;
    maxLength?: number;
    minItems?: number;
    maxItems?: number;
    title?: string;
    description?: string;
    [key: string]: unknown;
}

export interface OpenApiDocument {
    components?: { schemas?: Record<string, SchemaNode> };
}

const REF_PREFIX = '#/components/schemas/';

/** Keywords that carry no validation semantics and are skipped without complaint. */
const IGNORED_KEYWORDS = new Set([
    'title',
    'description',
    'examples',
    'example',
    'deprecated',
    'default',
    'readOnly',
    'writeOnly',
    'externalDocs',
]);

/** Keywords the emitter acts on; anything not here or in `IGNORED_KEYWORDS` (or `x-` prefixed) fails generation. */
const HANDLED_KEYWORDS = new Set([
    '$ref',
    'type',
    'properties',
    'required',
    'additionalProperties',
    'items',
    'allOf',
    'anyOf',
    'oneOf',
    'discriminator',
    'enum',
    'const',
    'format',
    'pattern',
    'minimum',
    'maximum',
    'exclusiveMinimum',
    'exclusiveMaximum',
    'multipleOf',
    'minLength',
    'maxLength',
    'minItems',
    'maxItems',
]);

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/** Names the generated module already uses, which a schema cannot take without shadowing them. */
const RESERVED_NAMES = new Set(['z']);

const INDENT = '    ';

export const COMMENT_HEADER = `/**
 * This file was auto-generated by \`scripts/generate_schemas.mts\`.
 * Do not make direct changes to the file.
 */

`;

/**
 * Emits the whole module: header, the zod import and one `export const` per schema, in dependency order so
 * that every reference names a constant declared above it.
 */
export function emitSchemas(document: OpenApiDocument): string {
    const schemas = document.components?.schemas;
    if (!schemas || Object.keys(schemas).length === 0) {
        throw new Error('The specification has no `components.schemas` to generate from.');
    }

    for (const name of Object.keys(schemas)) {
        if (!IDENTIFIER.test(name) || RESERVED_NAMES.has(name)) {
            throw new Error(`Schema name "${name}" is not usable as an exported identifier.`);
        }
    }

    const emitter = new Emitter(schemas);
    const declarations = emitter.orderedNames().map((name) => emitter.declaration(name));

    return `${COMMENT_HEADER}import { z } from 'zod';\n\n${declarations.join('\n\n')}\n`;
}

/**
 * Emits the zod expression for one schema node, as it would appear inside the generated module. Exposed for
 * tests; `emitSchemas()` is the entry point for generation.
 */
export function emitSchema(node: SchemaNode, schemas: Record<string, SchemaNode> = {}): string {
    return new Emitter(schemas).expression(node, 'schema', '');
}

class Emitter {
    private readonly schemas: Record<string, SchemaNode>;

    constructor(schemas: Record<string, SchemaNode>) {
        this.schemas = schemas;
    }

    /**
     * Every schema after the ones it references. A reference cycle is rejected: none exists today, and
     * supporting one takes `z.lazy()` plus explicit type annotations, so it should be a deliberate addition.
     */
    orderedNames(): string[] {
        const ordered: string[] = [];
        const state = new Map<string, 'visiting' | 'done'>();

        const visit = (name: string, trail: string[]) => {
            const current = state.get(name);
            if (current === 'done') return;
            if (current === 'visiting') {
                throw new Error(`Reference cycle among schemas: ${[...trail, name].join(' -> ')}.`);
            }
            state.set(name, 'visiting');
            for (const dependency of this.references(this.schema(name, name))) visit(dependency, [...trail, name]);
            state.set(name, 'done');
            ordered.push(name);
        };

        for (const name of Object.keys(this.schemas)) visit(name, []);
        return ordered;
    }

    declaration(name: string): string {
        const node = this.schema(name, name);
        const doc = node.description ? `${docComment(node.description)}\n` : '';
        return `${doc}export const ${name} = ${this.expression(node, name, '')};`;
    }

    expression(node: SchemaNode, path: string, indent: string): string {
        this.assertSupportedKeywords(node, path);

        if (node.$ref !== undefined) return this.reference(node, path);
        if (node.allOf) return this.allOf(node, path, indent);
        if (node.oneOf) return this.oneOf(node, path, indent);
        if (node.anyOf) return this.anyOf(node, path, indent);
        if (node.const !== undefined) return withNullable(`z.literal(${JSON.stringify(node.const)})`, node);
        if (node.enum) return this.enumeration(node, path);

        const types = typesOf(node);
        if (types.length === 0) {
            if (node.properties || node.additionalProperties !== undefined) return this.object(node, path, indent);
            return isNullableType(node) ? 'z.null()' : 'z.unknown()';
        }

        const members = types.map((type) => this.typed(type, node, path, indent));
        return withNullable(members.length === 1 ? members[0] : `z.union([${members.join(', ')}])`, node);
    }

    private typed(type: string, node: SchemaNode, path: string, indent: string): string {
        switch (type) {
            case 'string':
                return this.string(node, path);
            case 'integer':
                return numeric('z.int()', node);
            case 'number':
                return numeric('z.number()', node);
            case 'boolean':
                return 'z.boolean()';
            case 'array':
                return this.array(node, path, indent);
            case 'object':
                return this.object(node, path, indent);
            default:
                throw new Error(`Unsupported type "${type}" at ${path}.`);
        }
    }

    private reference(node: SchemaNode, path: string): string {
        const name = refName(node.$ref!, path);
        this.schema(name, path);
        // `hoistRefSiblingRequired()` has moved a `required` next to a `$ref` inside an `allOf` up to the parent
        // by the time this runs. One anywhere else has no place to go, so it is an error rather than a drop.
        for (const key of Object.keys(node)) {
            if (key !== '$ref' && !IGNORED_KEYWORDS.has(key) && !key.startsWith('x-')) {
                throw new Error(`A $ref at ${path} carries "${key}", which cannot be applied to a reference.`);
            }
        }
        return name;
    }

    private string(node: SchemaNode, path: string): string {
        if (node.format === 'date-time') return 'z.date()';

        let out = 'z.string()';
        if (node.minLength !== undefined) out += `.min(${node.minLength})`;
        if (node.maxLength !== undefined) out += `.max(${node.maxLength})`;
        if (node.pattern !== undefined) out += `.regex(${regexLiteral(node.pattern, path)})`;
        return out;
    }

    private array(node: SchemaNode, path: string, indent: string): string {
        const items = node.items ? this.expression(node.items, `${path}/items`, indent) : 'z.unknown()';
        let out = `z.array(${items})`;
        if (node.minItems !== undefined) out += `.min(${node.minItems})`;
        if (node.maxItems !== undefined) out += `.max(${node.maxItems})`;
        return out;
    }

    private object(node: SchemaNode, path: string, indent: string): string {
        const additional = node.additionalProperties;
        const values =
            typeof additional === 'object'
                ? this.expression(additional, `${path}/additionalProperties`, indent)
                : 'z.unknown()';

        if (!node.properties) return `z.record(z.string(), ${values})`;

        const shape = this.shape(node.properties, node.required ?? [], path, indent);
        // `additionalProperties: false` is deliberately not `z.strictObject()`: unknown fields in a response
        // must pass through, whatever the specification says about them.
        return typeof additional === 'object'
            ? `z.looseObject(${shape}).catchall(${values})`
            : `z.looseObject(${shape})`;
    }

    private shape(properties: Record<string, SchemaNode>, required: string[], path: string, indent: string): string {
        const inner = indent + INDENT;
        const lines = Object.entries(properties).map(([key, property]) => {
            const value = this.expression(property, `${path}/properties/${key}`, inner);
            const optional = required.includes(key) ? '' : '.optional()';
            return `${inner}${propertyKey(key)}: ${value}${optional},`;
        });
        return lines.length === 0 ? '{}' : `{\n${lines.join('\n')}\n${indent}}`;
    }

    /**
     * `allOf` over objects becomes `.extend()` calls on the first member, so the result is still a
     * `ZodObject` -- with a `.shape` and `.extend()` of its own for a hand-written override to build on. A
     * `required` that names fields of the base is applied with `.required()`, which is what a hoisted
     * `$ref`-sibling `required` and a member that carries only `required` both come down to. Members that are
     * not objects fall back to `z.intersection()`.
     */
    private allOf(node: SchemaNode, path: string, indent: string): string {
        const [first, ...rest] = node.allOf!;
        if (!first) throw new Error(`Empty allOf at ${path}.`);

        const forbidden = Object.keys(node).filter(
            (key) => !['allOf', 'properties', 'required', 'type'].includes(key) && !isIgnorable(key),
        );
        if (forbidden.length > 0) {
            throw new Error(`allOf at ${path} combined with "${forbidden.join('", "')}" is not supported.`);
        }
        if (node.type !== undefined && node.type !== 'object') {
            throw new Error(`allOf at ${path} with type "${String(node.type)}" is not supported.`);
        }

        let out = this.expression(first, `${path}/allOf[0]`, indent);
        const required = new Set(node.required ?? []);

        const members = rest.map((member, index) => ({ member, path: `${path}/allOf[${index + 1}]` }));
        if (node.properties) members.push({ member: { properties: node.properties }, path });

        if (!this.isObjectSchema(first)) {
            const others = members.map(({ member, path: memberPath }) => this.expression(member, memberPath, indent));
            return withRequired(
                [out, ...others].reduce((a, b) => `z.intersection(${a}, ${b})`),
                required,
                path,
            );
        }

        for (const { member, path: memberPath } of members) {
            this.assertSupportedKeywords(member, memberPath);
            for (const key of member.required ?? []) required.add(key);

            if (member.$ref !== undefined) {
                out += `.extend(${this.reference(member, memberPath)}.shape)`;
            } else if (member.properties) {
                if (member.type !== undefined && member.type !== 'object') {
                    throw new Error(`allOf member at ${memberPath} has type "${String(member.type)}".`);
                }
                out += `.extend(${this.shape(member.properties, member.required ?? [], memberPath, indent)})`;
                for (const key of member.required ?? []) if (key in member.properties) required.delete(key);
            } else if (Object.keys(member).some((key) => key !== 'required' && key !== 'type' && !isIgnorable(key))) {
                throw new Error(`allOf member at ${memberPath} is neither a $ref nor an object with properties.`);
            }
        }

        return withRequired(out, required, path);
    }

    private oneOf(node: SchemaNode, path: string, indent: string): string {
        const members = node.oneOf!.map((member, index) => this.expression(member, `${path}/oneOf[${index}]`, indent));
        const discriminator = node.discriminator?.propertyName;
        if (
            discriminator !== undefined &&
            node.oneOf!.every((member) => this.hasConstProperty(member, discriminator))
        ) {
            return withNullable(
                `z.discriminatedUnion(${JSON.stringify(discriminator)}, [${members.join(', ')}])`,
                node,
            );
        }
        return withNullable(`z.union([${members.join(', ')}])`, node);
    }

    /** `anyOf: [X, { type: 'null' }]` is how the specification spells a nullable reference. */
    private anyOf(node: SchemaNode, path: string, indent: string): string {
        const members = node.anyOf!.filter((member) => !isNullOnly(member));
        const nullable = members.length < node.anyOf!.length;
        const expressions = members.map((member, index) => this.expression(member, `${path}/anyOf[${index}]`, indent));
        const out = expressions.length === 1 ? expressions[0] : `z.union([${expressions.join(', ')}])`;
        return nullable ? `${out}.nullable()` : withNullable(out, node);
    }

    private enumeration(node: SchemaNode, path: string): string {
        const values = node.enum!.filter((value) => value !== null);
        const nullable = values.length < node.enum!.length || isNullableType(node);
        if (!values.every((value) => typeof value === 'string')) {
            throw new Error(`Only string enums are supported, at ${path}.`);
        }
        const out = `z.enum([${values.map((value) => JSON.stringify(value)).join(', ')}]).or(z.string())`;
        return nullable ? `${out}.nullable()` : out;
    }

    private isObjectSchema(node: SchemaNode): boolean {
        if (node.$ref !== undefined) return this.isObjectSchema(this.schema(refName(node.$ref, node.$ref), node.$ref));
        if (node.allOf) return node.allOf.length > 0 && this.isObjectSchema(node.allOf[0]);
        return node.properties !== undefined || node.type === 'object';
    }

    /** Whether the schema, or an `allOf` member of it, declares `name` as a `const` -- what a discriminator needs. */
    private hasConstProperty(node: SchemaNode, name: string): boolean {
        if (node.$ref !== undefined)
            return this.hasConstProperty(this.schema(refName(node.$ref, node.$ref), node.$ref), name);
        if (node.properties?.[name]?.const !== undefined) return true;
        return (node.allOf ?? []).some((member) => this.hasConstProperty(member, name));
    }

    private references(node: unknown, found = new Set<string>()): Set<string> {
        if (Array.isArray(node)) {
            for (const item of node) this.references(item, found);
        } else if (node && typeof node === 'object') {
            for (const [key, value] of Object.entries(node)) {
                if (key === '$ref' && typeof value === 'string') found.add(refName(value, value));
                else if (!IGNORED_KEYWORDS.has(key)) this.references(value, found);
            }
        }
        return found;
    }

    private schema(name: string, path: string): SchemaNode {
        const node = this.schemas[name];
        if (!node) throw new Error(`Unknown schema "${name}" referenced at ${path}.`);
        return node;
    }

    private assertSupportedKeywords(node: SchemaNode, path: string): void {
        for (const key of Object.keys(node)) {
            if (!HANDLED_KEYWORDS.has(key) && !isIgnorable(key)) {
                throw new Error(`Unsupported keyword "${key}" at ${path}.`);
            }
        }
    }
}

function isIgnorable(key: string): boolean {
    return IGNORED_KEYWORDS.has(key) || key.startsWith('x-');
}

/** The non-null entries of `type`, which OpenAPI 3.1 may spell as an array. */
function typesOf(node: SchemaNode): string[] {
    const types = node.type === undefined ? [] : Array.isArray(node.type) ? node.type : [node.type];
    return types.filter((type) => type !== 'null');
}

function isNullableType(node: SchemaNode): boolean {
    return Array.isArray(node.type) ? node.type.includes('null') : node.type === 'null';
}

function isNullOnly(node: SchemaNode): boolean {
    return node.type === 'null' && Object.keys(node).every((key) => key === 'type' || isIgnorable(key));
}

function withNullable(expression: string, node: SchemaNode): string {
    return isNullableType(node) ? `${expression}.nullable()` : expression;
}

function withRequired(expression: string, required: Set<string>, path: string): string {
    if (required.size === 0) return expression;
    for (const key of required) {
        if (!IDENTIFIER.test(key)) throw new Error(`Required key "${key}" at ${path} is not an identifier.`);
    }
    return `${expression}.required({ ${[...required].map((key) => `${key}: true`).join(', ')} })`;
}

function numeric(base: string, node: SchemaNode): string {
    let out = base;
    if (node.minimum !== undefined) out += `.min(${node.minimum})`;
    if (node.maximum !== undefined) out += `.max(${node.maximum})`;
    if (node.exclusiveMinimum !== undefined) out += `.gt(${node.exclusiveMinimum})`;
    if (node.exclusiveMaximum !== undefined) out += `.lt(${node.exclusiveMaximum})`;
    if (node.multipleOf !== undefined) out += `.multipleOf(${node.multipleOf})`;
    return out;
}

function refName(ref: string, path: string): string {
    if (!ref.startsWith(REF_PREFIX))
        throw new Error(`Only references into components.schemas are supported, at ${path}.`);
    return ref.slice(REF_PREFIX.length);
}

function propertyKey(key: string): string {
    return IDENTIFIER.test(key) ? key : JSON.stringify(key);
}

function regexLiteral(pattern: string, path: string): string {
    try {
        new RegExp(pattern);
    } catch (error) {
        throw new Error(`Pattern at ${path} is not a valid regular expression: ${(error as Error).message}`);
    }
    if (/[\n\r]/.test(pattern)) throw new Error(`Pattern at ${path} contains a line break.`);
    return `/${pattern.replaceAll(/(?<!\\)\//g, '\\/')}/`;
}

function docComment(description: string): string {
    const lines = description.trim().replaceAll('*/', '*\\/').split('\n');
    if (lines.length === 1) return `/** ${lines[0]} */`;
    return `/**\n${lines.map((line) => ` * ${line}`.trimEnd()).join('\n')}\n */`;
}
