module.exports = [[
    {
        type: 'category',
        label: 'API Client',
        items: [
            'index',
            'features',
            'usage_concepts',
        ],
    },
    // {
    //     type: 'category',
    //     label: 'Examples',
    //     items: [
    //         {
    //             type: 'autogenerated',
    //             dirName: 'examples',
    //         },
    //     ],
    // },
    {
        type: 'doc',
        id: 'changelog',
    },
]];
